### ISSUE TITLE
Move alice example in another subfolder

### ISSUE THREAD

**Issue by zuphilip** [kba/ocr-fileformat-samples#6]
The example https://github.com/kba/ocr-fileformat-samples/blob/master/samples/hocr/1.1/alice.hocr seems to be so much outdated and not anymore conform with the specs or any current output, that I think we might want to delete it or maybe move it into another folder, say `/hocr/1.0` or `/hocr/v2007/`? I guess we have something like version from 2007 and version from 2010.

**Comment by kba** [comment]
That is a good idea.

**Comment by zuphilip** [comment]
What is version hocr version 1.1 exactly? And where do you suggest to move it?

**Comment by kba** [comment]
I made it up :) https://github.com/kba/hocr-spec/releases/tag/1.1.0 I called the version in GoogleDoc that has been around since 2009 version 1.0.0 and started rearranging things.

`v2007` is probably a good indicator of how old and uncertain it is. Could also use the Ocropus revision.
